language: c
compiler:
  - clang
  - gcc
install:
  - if [ -z "$TRAVIS_OS_NAME" ]; then export TRAVIS_OS_NAME=linux; fi # for forks that do not have multi-os enabled
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then travis_retry sudo apt-get install -qq libssl-dev; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$BIGNUM" = "gmp" -o "$BIGNUM" = "auto" ]; then travis_retry sudo apt-get install --no-install-recommends --no-upgrade -qq libgmp-dev; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ -n "$EXTRAPACKAGES" ]; then travis_retry sudo apt-get update && travis_retry sudo apt-get install --no-install-recommends --no-upgrade $EXTRAPACKAGES; fi
env:
  global:
    - FIELD=auto  BIGNUM=auto  SCALAR=auto  ENDOMORPHISM=no  ASM=no  BUILD=check  EXTRAFLAGS= HOST= EXTRAPACKAGES=
  matrix:
    - SCALAR=32bit
    - SCALAR=64bit
    - FIELD=64bit
    - FIELD=64bit     ENDOMORPHISM=yes
    - FIELD=64bit                       ASM=x86_64
    - FIELD=64bit     ENDOMORPHISM=yes  ASM=x86_64
    - FIELD=32bit
    - FIELD=32bit     ENDOMORPHISM=yes
    - BIGNUM=no
    - BIGNUM=no       ENDOMORPHISM=yes
    - BUILD=distcheck
    - EXTRAFLAGS=CFLAGS=-DDETERMINISTIC
    - HOST=i686-linux-gnu EXTRAPACKAGES="gcc-multilib"
    - HOST=i686-linux-gnu EXTRAPACKAGES="gcc-multilib" ENDOMORPHISM=yes
before_script: ./autogen.sh
script:
  - if [ -n "$HOST" ]; then export USE_HOST="--host=$HOST"; fi
  - if [ "x$HOST" = "xi686-linux-gnu" ]; then export CC="$CC -m32"; fi
  - ./configure --enable-endomorphism=$ENDOMORPHISM --with-field=$FIELD --with-bignum=$BIGNUM --with-scalar=$SCALAR $EXTRAFLAGS $USE_HOST && make -j2 $BUILD
os:
  - linux
  - osx
